/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.2.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Gradle Tooling API releases.
    maven { url = uri("https://repo.gradle.org/gradle/libs-releases") }
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // The Gradle Tooling API, used to embed Gradle into the C++ library.
    implementation("org.gradle:gradle-tooling-api:9.2.0")
    // The Tooling API needs an SLF4J implementation at runtime.
    runtimeOnly("org.slf4j:slf4j-simple:2.0.17")

    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Compile to Java 8 bytecode (the Tooling API is Java 8 compatible) using
// whatever JDK is available, so no toolchain download is required.
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Build a self-contained fat jar (bridge + tooling-api + slf4j) without
// relying on the Shadow plugin, so the build has no extra plugin downloads.
val fatJar = tasks.register<Jar>("fatJar") {
    archiveBaseName.set("gradle-runner-bridge")
    archiveClassifier.set("")
    archiveVersion.set("")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    manifest {
        attributes["Main-Class"] = "com.anthony.GradleRunnerBridge"
    }

    from(sourceSets.main.get().output)

    dependsOn(configurations.runtimeClasspath)
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }
            .map { zipTree(it) }
    })
}

tasks.named("build") {
    dependsOn(fatJar)
}
